version: '3.2'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/project.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ./config/php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./var/data/mysql:/var/lib/mysql:cached
      - ./config/mysql/my.cnf:/etc/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8089:80"
    links:
      - db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8025:80"
